#!/bin/bash

# Slurm job options (name, compute nodes, job time)
#SBATCH --job-name=pingpong
#SBATCH --time=00:05:00
#SBATCH --output=%x-%j.out
#SBATCH --nodes=1
#SBATCH --tasks-per-node=2
#SBATCH --cpus-per-task=1
#SBATCH --partition=standard
#SBATCH --qos=short

export OMP_NUM_THREADS=1

ulimit -s unlimited

export SRUN_CPUS_PER_TASK=${SLURM_CPUS_PER_TASK}

# Launch the parallel job

srun --unbuffered --distribution=block:block --hint=nomultithread ./pingpong
